//! Submit a built MSIX bundle to the Microsoft Store via the Store submission
//! API, so a tagged release reaches certification without a manual Partner
//! Center upload.
//!
//! Usage: `node scripts/submit-store.mjs <package.zip> <assets-dir>`
//!
//! The zip must contain the `.msixbundle`, the screenshots named by
//! `packaging/windows/store-listing.json`, and the trailer pair — all flat, at
//! the zip root, which is how the submission JSON references them.
//! `<assets-dir>` is the same set of listing files on disk, so the script can
//! check every one exists before it touches the live listing.
//!
//! Release notes come from `CHANGELOG.md`. Screenshots and the trailer are
//! regenerated by the `store-assets` job from the build this release ships, so
//! the listing cannot show UI that no longer exists.
//!
//! Credentials come from the
//! environment: `MSSTORE_TENANT_ID`, `MSSTORE_CLIENT_ID`,
//! `MSSTORE_CLIENT_SECRET` — an Azure AD application associated with the
//! Partner Center account and granted the **Manager** role.
//!
//! Two constraints from the API, both load-bearing:
//!
//! - A submission created through the API must only ever be *changed* through
//!   the API. Editing it in Partner Center leaves it uncommittable and it has
//!   to be deleted and recreated. So: once this runs, finish in the API or
//!   delete the pending submission.
//! - The app must already have one manually completed submission, including
//!   the age-ratings questionnaire. This script updates an existing listing;
//!   it cannot create one.
//!
//! Docs: https://learn.microsoft.com/en-us/windows/uwp/monetize/manage-app-submissions

import assert from "node:assert/strict";
import { access, appendFile, readFile } from "node:fs/promises";
import path from "node:path";

import { changelogSection, msixVersion, releaseVersion, root } from "./release-version.mjs";

const API = "https://manage.devcenter.microsoft.com/v1.0/my";
/** Certification takes hours; this only waits for the commit to be accepted. */
const COMMIT_POLL_ATTEMPTS = 40;
const COMMIT_POLL_INTERVAL_MS = 15_000;

const packageZip = process.argv[2];
assert.ok(packageZip, "usage: node scripts/submit-store.mjs <package.zip>");

const { MSSTORE_TENANT_ID, MSSTORE_CLIENT_ID, MSSTORE_CLIENT_SECRET } = process.env;
const missing = Object.entries({
  MSSTORE_TENANT_ID,
  MSSTORE_CLIENT_ID,
  MSSTORE_CLIENT_SECRET,
})
  .filter(([, value]) => !value)
  .map(([name]) => name);

// Absent credentials mean the Entra application has not been set up yet, which
// is a legitimate state — the manual Partner Center upload reaches exactly the
// same place. Say so loudly and hand back the manual steps, but do not fail the
// release build over it. A *broken* credential still fails hard below; only a
// wholly unconfigured one skips.
if (missing.length === 3) {
  const identity = JSON.parse(
    await readFile(path.join(root, "packaging/windows/store-identity.json"), "utf8"),
  );
  const steps = [
    "Store submission skipped: no Microsoft Entra credentials configured.",
    "",
    `Upload \`${path.basename(packageZip, ".zip")}.msixbundle\` by hand instead:`,
    "",
    `1. Download the \`windows-store-msixbundle\` artifact from this run.`,
    `2. In Partner Center, open product \`${identity.productId}\` and create a submission.`,
    `3. Upload the bundle (version ${msixVersion(await releaseVersion())}) and submit for certification.`,
    "",
    "To automate this next time, see the Microsoft Entra setup in docs/releasing.md.",
    "No company or paid subscription is needed — a free tenant can be created",
    "from inside Partner Center.",
  ].join("\n");

  console.warn(`::warning title=Store submission skipped::${steps.split("\n")[0]}`);
  if (process.env.GITHUB_STEP_SUMMARY) {
    await appendFile(process.env.GITHUB_STEP_SUMMARY, `## Microsoft Store\n\n${steps}\n`);
  }
  console.log(steps);
  process.exit(0);
}

// A partial configuration is a mistake, not a choice — fail rather than
// silently skipping a submission the operator believes is wired up.
assert.equal(
  missing.length,
  0,
  `incomplete Store credentials: ${missing.join(", ")} not set. ` +
    "Set all three or none (none skips submission with instructions).",
);

// Checked only once credentials are known to be complete, so the no-credentials
// skip above stays the cheap "nothing is wired up yet" path.
const assetsDir = process.argv[3];
assert.ok(assetsDir, "usage: node scripts/submit-store.mjs <package.zip> <assets-dir>");

const identity = JSON.parse(
  await readFile(path.join(root, "packaging/windows/store-identity.json"), "utf8"),
);
const version = await releaseVersion();
assert.equal(
  identity.msixVersion,
  msixVersion(version),
  "store-identity.json msixVersion is out of step with plugins/nodestorm/VERSION",
);

/** The Store ID from Partner Center, e.g. `9PL98XH1NQZB`. */
const applicationId = identity.productId;

const listingCopy = JSON.parse(
  await readFile(path.join(root, "packaging/windows/store-listing.json"), "utf8"),
);
/** Flat names, matching how the workflow zips the assets. */
const TRAILER_VIDEO = "trailer.mp4";
const TRAILER_THUMBNAIL = "trailer-thumb.png";
// The Store renders release notes as plain text, so `### Added` would show its
// hashes. The GitHub release keeps the Markdown; only this copy is flattened.
const releaseNotes = (await changelogSection(version)).replace(/^#+ /gm, "");

// Check the assets before the first API call. A submission that references a
// file the zip does not carry fails at commit, after the live listing already
// holds a pending submission someone then has to clean up by hand.
for (const file of [
  ...listingCopy.screenshots.map((shot) => shot.file),
  TRAILER_VIDEO,
  TRAILER_THUMBNAIL,
]) {
  try {
    await access(path.join(assetsDir, file));
  } catch (error) {
    throw new Error(`listing asset missing from ${assetsDir}: ${file}`, { cause: error });
  }
}

async function token() {
  const body = new URLSearchParams({
    grant_type: "client_credentials",
    client_id: MSSTORE_CLIENT_ID,
    client_secret: MSSTORE_CLIENT_SECRET,
    resource: "https://manage.devcenter.microsoft.com",
  });
  const response = await fetch(
    `https://login.microsoftonline.com/${MSSTORE_TENANT_ID}/oauth2/token`,
    { method: "POST", body },
  );
  if (!response.ok) {
    throw new Error(`Azure AD token request failed: ${response.status} ${await response.text()}`);
  }
  return (await response.json()).access_token;
}

const accessToken = await token();

async function api(method, endpoint, body) {
  const response = await fetch(`${API}${endpoint}`, {
    method,
    headers: {
      Authorization: `Bearer ${accessToken}`,
      ...(body ? { "Content-Type": "application/json" } : {}),
    },
    ...(body ? { body: JSON.stringify(body) } : {}),
  });
  const text = await response.text();
  if (!response.ok) {
    throw new Error(`${method} ${endpoint} failed: ${response.status} ${text}`);
  }
  return text ? JSON.parse(text) : {};
}

// A pending submission blocks a new one. Reclaim it rather than failing --
// a previous run that died between create and commit would otherwise wedge
// every later release until someone cleaned up by hand.
const app = await api("GET", `/applications/${applicationId}`);
if (app.pendingApplicationSubmission?.id) {
  const stale = app.pendingApplicationSubmission.id;
  console.log(`Deleting stale pending submission ${stale}.`);
  await api("DELETE", `/applications/${applicationId}/submissions/${stale}`);
}

// Create: clones the last published submission, so listing text, pricing, and
// age ratings carry over untouched and only the packages change.
const submission = await api("POST", `/applications/${applicationId}/submissions`);
console.log(`Created submission ${submission.id} for ${applicationId}.`);

const bundleName = path.basename(packageZip).replace(/\.zip$/, ".msixbundle");
submission.applicationPackages = [
  // Retire what the previous submission shipped...
  ...submission.applicationPackages.map((pkg) => ({ ...pkg, fileStatus: "PendingDelete" })),
  // ...and add this build, named by its path inside the uploaded zip.
  { fileName: bundleName, fileStatus: "PendingUpload" },
];

// The clone also carries the previous release's listing text and artwork —
// which is how a release ends up showing the release before it. Refresh both:
// notes from the changelog, screenshots and trailer from the build shipping now.
//
// Trailers need the account's advanced listing permission; without it the field
// comes back null and cannot be set. That is an account capability, not a build
// problem — rerunning cannot fix it, so warn and still ship notes + screenshots.
const trailersSupported = app.hasAdvancedListingPermission !== false;
if (!trailersSupported) {
  console.warn(
    "::warning title=Trailer skipped::The account lacks advanced listing permission, so the Store trailer was not updated.",
  );
}

for (const [language, listing] of Object.entries(submission.listings)) {
  listing.baseListing.releaseNotes = releaseNotes;
  listing.baseListing.images = [
    // Retire only the superseded screenshots. Everything else in this array is
    // a hand-uploaded store logo, and sweeping those into PendingDelete would
    // strip artwork this pipeline cannot regenerate.
    ...listing.baseListing.images.map((image) =>
      image.imageType === "Screenshot" ? { ...image, fileStatus: "PendingDelete" } : image,
    ),
    ...listingCopy.screenshots.map((shot) => ({
      fileName: shot.file,
      fileStatus: "PendingUpload",
      imageType: "Screenshot",
      description: shot.caption,
    })),
  ];
  if (trailersSupported) {
    listing.trailers = [
      {
        videoFileName: TRAILER_VIDEO,
        trailerAssets: {
          [language]: {
            title: listingCopy.trailerTitle,
            imageList: [{ fileName: TRAILER_THUMBNAIL, description: listingCopy.trailerTitle }],
          },
        },
      },
    ];
  }
  console.log(
    `Refreshed the ${language} listing: release notes, ${listingCopy.screenshots.length} screenshots` +
      `${trailersSupported ? ", trailer" : ""}.`,
  );
}

await api("PUT", `/applications/${applicationId}/submissions/${submission.id}`, submission);

// The SAS URI is a single block blob: one PUT of the whole zip. Use the URI
// exactly as the API returned it — its signature is already percent-encoded,
// and re-encoding any of it invalidates the signature.
const archive = await readFile(packageZip);
const upload = await fetch(submission.fileUploadUrl, {
  method: "PUT",
  headers: { "x-ms-blob-type": "BlockBlob" },
  body: archive,
});
if (!upload.ok) {
  throw new Error(`Package upload failed: ${upload.status} ${await upload.text()}`);
}
console.log(`Uploaded ${bundleName} (${archive.length} bytes).`);

await api("POST", `/applications/${applicationId}/submissions/${submission.id}/commit`);
console.log("Commit requested; waiting for the Store to accept it.");

for (let attempt = 0; attempt < COMMIT_POLL_ATTEMPTS; attempt++) {
  const { status, statusDetails } = await api(
    "GET",
    `/applications/${applicationId}/submissions/${submission.id}/status`,
  );
  if (status === "CommitFailed") {
    throw new Error(`Store rejected the commit: ${JSON.stringify(statusDetails, null, 2)}`);
  }
  if (status !== "CommitStarted") {
    console.log(`Submission ${submission.id} accepted: ${status}. Certification continues in Partner Center.`);
    process.exit(0);
  }
  await new Promise((resolve) => setTimeout(resolve, COMMIT_POLL_INTERVAL_MS));
}

throw new Error(
  `Commit still pending after ${(COMMIT_POLL_ATTEMPTS * COMMIT_POLL_INTERVAL_MS) / 1000}s; check Partner Center.`,
);
